FROM ubuntu:16.04
MAINTAINER daniel
ENV MYSQL_PWD 80650390
RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get install ssh -y \
    && apt-get install sshpass -y \
    && apt-get install inetutils-ping -y \  
    && apt-get install lynx -y \
    && apt-get install ftp -y \
    && apt-get install ssh -y \
    && apt-get install vsftpd -y \
    && apt-get install rsync -y \
    && apt-get install nano -y \
    && apt-get upgrade -y \
    && echo "mysql-server mysql-server/root_password password $MYSQL_PWD" | debconf-set-selections \
    && echo "mysql-server mysql-server/root_password_again password $MYSQL_PWD" | debconf-set-selections \
    && apt-get install mysql-server -y \
    && usermod -d /var/lib/mysql/ mysql \
    && apt-get install sudo -y

CMD ["/bin/bash" ]

# use start.sh to trigger service
# COPY start.sh /
# CMD ["/start.sh"]
